controllers:
    resource: ../../src/Controller/
    type: annotation
#web_controller:
#    resource: ../../src/Infrastructure/Controller/Web/
#    type: annotation
rest_controller:
    resource: ../../src/Controller/
    type: annotation
    prefix: /api
