##index:
##    path: /
##    controller: App\Controller\DefaultController::index
#facebook_login:
#    path: /login/check-facebook
#
#google_login:
#    path: /login/check-google
#
#custom_login:
#    path: /login/check-custom
#
#github_login:
#    path: /login/check-github
api_login_check:
    path: /api/login_check